---
- name: Enable network discovery.
  ansible.windows.win_powershell:
    script: |
      netsh advfirewall firewall set rule group=”network discovery” new enable=yes
      netsh firewall set service type=fileandprint mode=enable profile=all
